### PR TITLE
Update to latest API. Fix #10

### LINKED ISSUE #10: Getting FileUriExposedException on Nougat
On Android Nougat you can't expose a file:// Uri anymore. We need to set a provider and share the Uri of the taken picture with it.

### PR DESCRIPTION
**Pull request by paolorotolo**
Update to target API 25.
Fix FileUriExposedException on Nougat (#10).

### CODE REVIEW

**Comment by chsienki** [comment]
Looks good, thanks for fixing this.

@cthrash Any objections to updating the SDKs/Gradle at the same time?

**Comment by cthrash** [comment]
My general rule of thumb is I ask myself: will rolling back the whole change if you have to revert the commit for whatever reason, a painful rollback?  Downgradinbag gradle is probably not the most painful thing, but it's likely a hassle. So if this were production code I would prefer splitting.  But since this is the sample app, I would totally let it slide.

**Comment by paolorotolo** [comment]
Sure, I totally understand this. I made two different commits in my PR, one for updates and the other one to fix the issue. You can rebase and merge this pull to keep the commits individually.

**Comment by paolorotolo** [comment]
Sure, I totally understand this. I can open another PR with the two commit split if you'd like.

**Comment by chsienki** [comment]
Looping back on this. The actual changes are in two commits anyway, so we can already easily revert the gradle changes if needed; submitting as two PRs doesn't change that. Merging.

**Pull request merged**
